// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jairogloz/go-l/pkg/ports (interfaces: LeagueService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_league_service.go -package=mocks github.com/jairogloz/go-l/pkg/ports LeagueService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/jairogloz/go-l/pkg/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLeagueService is a mock of LeagueService interface.
type MockLeagueService struct {
	ctrl     *gomock.Controller
	recorder *MockLeagueServiceMockRecorder
	isgomock struct{}
}

// MockLeagueServiceMockRecorder is the mock recorder for MockLeagueService.
type MockLeagueServiceMockRecorder struct {
	mock *MockLeagueService
}

// NewMockLeagueService creates a new mock instance.
func NewMockLeagueService(ctrl *gomock.Controller) *MockLeagueService {
	mock := &MockLeagueService{ctrl: ctrl}
	mock.recorder = &MockLeagueServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeagueService) EXPECT() *MockLeagueServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLeagueService) Create(ctx context.Context, league *domain.League) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, league)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLeagueServiceMockRecorder) Create(ctx, league any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLeagueService)(nil).Create), ctx, league)
}

// Delete mocks base method.
func (m *MockLeagueService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLeagueServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLeagueService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockLeagueService) Get(ctx context.Context, id string) (*domain.League, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.League)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLeagueServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLeagueService)(nil).Get), ctx, id)
}
